package gcode

import (
	"bytes"
	"testing"
)

func TestPatchGCodeTime(t *testing.T) {
	tests := []struct {
		name string
		in   string
		want string
	}{
		{
			name: "no G28 unchanged",
			in:   "; estimated printing time = 1h 2m\nG1 X1 Y1\n",
			want: "; estimated printing time = 1h 2m\nG1 X1 Y1\n",
		},
		{
			name: "insert TIME before first G28",
			in:   "; estimated printing time = 1h 2m 3s\nM104 S200\nG28\nG1 X1 Y1\n",
			want: "; estimated printing time = 1h 2m 3s\nM104 S200\n;TIME:3723\nG28\nG1 X1 Y1\n",
		},
		{
			name: "existing TIME not duplicated",
			in:   ";TIME:42\n; estimated printing time = 1h 2m 3s\nG28\n",
			want: ";TIME:42\n; estimated printing time = 1h 2m 3s\nG28\n",
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			got := PatchGCodeTime([]byte(tt.in))
			if !bytes.Equal(got, []byte(tt.want)) {
				t.Fatalf("PatchGCodeTime() = %q, want %q", string(got), tt.want)
			}
		})
	}
}

func TestExtractLayerCount(t *testing.T) {
	tests := []struct {
		name    string
		in      string
		want    int
		wantHas bool
	}{
		{
			name:    "OrcaSlicer LAYER_COUNT header",
			in:      ";LAYER_COUNT:42\n; generated by OrcaSlicer\nG28\n",
			want:    42,
			wantHas: true,
		},
		{
			name:    "PrusaSlicer LAYER_CHANGE fallback",
			in:      "; generated by PrusaSlicer\nG28\n;LAYER_CHANGE\nG1 X1\n;LAYER_CHANGE\n;LAYER_CHANGE\n",
			want:    3,
			wantHas: true,
		},
		{
			name:    "no markers",
			in:      "; generated by slicer\nG28\nG1 X1\n",
			want:    0,
			wantHas: false,
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			got, ok := ExtractLayerCount([]byte(tt.in))
			if got != tt.want || ok != tt.wantHas {
				t.Fatalf("ExtractLayerCount() = (%d,%v), want (%d,%v)", got, ok, tt.want, tt.wantHas)
			}
		})
	}
}
